Update appveyor.yml

diff --git a/appveyor.yml b/appveyor.yml
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -44,12 +44,12 @@ build_script:
   set MAKE_COMMAND = make
 )
 - WHERE /q mingw32-make && (
-echo "'mingw32-make' found."
-set MAKE_COMMAND=mingw32-make
+  echo "'mingw32-make' found."
+  set MAKE_COMMAND=mingw32-make
 )
 - IF "%MAKE_COMMAND%"=="" (
-echo "Error: Neither 'make' nor 'mingw32-make' could be found."
-exit 1
+  echo "Error: Neither 'make' nor 'mingw32-make' could be found."
+  exit 1
 )
 - echo "Using '%MAKE_COMMAND%' .exe."
 - luarocks make MAKE=%MAKE_COMMAND%
